### ISSUE TITLE
Algo to deal with per subject pages

### ISSUE THREAD

**Issue by brechtvdv** [TREEcg/event-stream-client#10]
Use case: the event stream only contains the link to its members. Most of the information of a member needs to be retrieved by dereferencing the member.

LDES client must check by default if a member is compliant with the SHACL shape of the Event Stream. When this not compliant, then the client will dereference the member and add the retrieved information to the result.
When there is no SHACL shape available, the client will not dereference.

Optional to overwrite this behavior with parameter --dereference true | false

**Comment by pietercolpaert** [comment]
So by default: don’t derefence, unless there is a required property in the shape that isn’t provided in the triples about the member in this page, then we will also dereference it.

There should be indeed a configuration to turn it off.

Next step: it should also be possible to configure a BGP or a shape on the client and then decide automatically whether the member should also be dereferenced.

**Comment by pietercolpaert** [comment]
The option has been implemented. We can work on automating this option when we have shacl/shex support in the client.
