### ISSUE TITLE
Determining which triples need to be emitted per event-based object

### ISSUE THREAD

**Issue by brechtvdv** [TREEcg/event-stream-client#2]
You need to process each `tree:member` of collection as a separate object. 

To decide which triples of this object need to be returned, we use following strategy:

### Based on SHACL shape of the collection itself

_By default_, we follow all references (both subject and object references) until end, but detect cycles. ⇒ “possible blows up the objects, but this is the only right implementation?”

Example dataset:
```turtle
<C1> tree:member <A> .
<A> hasFriend <B> .
<C1> tree:member <B> .
<B> hasFriend <A> .
```
Desired behaviour: it must emit: 2 objects:

Focus node: A
```turtle
<C1> tree:member <A> .
<A> hasFriend <B> . 
<C1> tree:member <B> .
<B> hasFriend <A> .
```

Focus node: B
```turtle
<C1> tree:member <B> .
<B> hasFriend <A> .
<C1> tree:member <A> .
<A> hasFriend <B> .
 ```
 ⇒ This requires detection of cycles!!!

When there is a shape linked to the collection, do following:

- open `sh:ShapeNode`s: do nothing. These are useful for source selection, but not for recreating the object. This has the same effect as our defeault behaviour.
- closed `sh:ShapeNode`s and optionally has ignored properties, this is the more important case as we really need to parse the closed shape and use this to filter the triples of a focus node.

Iterate over all (ignored) properties of a closed `sh:NodeShape` and process these further

A possible implementation could be to convert closed shapes to a specific BGP SPARQL query. Then, we can use the Comunica SPARQL actor to execute this query 

Desired behaviour when shape contains only `hasFriend`:

Focus node: A 
```turtle
<A> hasFriend <B> .
```
 
Focus node: B
```turtle
<B> hasFriend <A> .
 ```

When shacl shape is broken and not valid: be forgiving → Don’t check cardinalities

### Using a client-side SPARQL query

You can configure a SPARQL query in comunica to select a subset of triples you want

In this case, ignore the first option 1, configure a sparql template query as follows:

```sparql
CONSTRUCT  * WHERE {
   {$member} ?p ?o .
}
```

**Comment by pietercolpaert** [comment]
Closing for now. The current approach is sufficient. Opening a more detailed issue later.
