### ISSUE TITLE
object.Identificator missing in Client

### ISSUE THREAD

**Issue by oliviervd** [TREEcg/event-stream-client#21]
Object.Identifcator ontbreekt nog in de client. Deze wordt wel getoond in gepubliceerde LDES.  
>> https://apidg.gent.be/opendata/adlib2eventstream/v1/dmg/objecten?generatedAtTime=2021-08-15T01:56:04.152Z

```
Object.identificator: [
{
@type: "Identificator",
Identificator.identificator: {
@value: "2019-0006",
@type: "undefinedidentificatiesysteem/objectnummer"
}
}
],
```

**Comment by pietercolpaert** [comment]
Opened an issue in the right place instead
