### ISSUE TITLE
Usage as NPM library

### ISSUE THREAD

**Issue by pietercolpaert** [TREEcg/event-stream-client#22]
For our [Github action code](https://github.com/TREEcg/gh-action-republish-ldes/blob/fragmentation/src/data.ts), we need better support for the LDES client to be used as an NPM library:

 * [x] Don’t emit serialized objects when used as a JS library: we can just use the RDFJS Quads. When emitting the RDFJS Quads, package them in an Array per `tree:member`. If the user requests to use JSON, translate the RDFJS quads to JSON using the existing code to add context.
      -  If JSON is used, how do you access the JSON-LD context of the emitted JSON objects? There’s no way to otherwise republish them as Linked Data 
 * [x] How does the collection’s metadata get exposed? I’m thinking about, the shape of the object, the Collection URI and other metadata such as title, author, license, etc (probably should also be part of https://github.com/TREEcg/tree-metadata-extraction)

**Comment by pietercolpaert** [comment]
Part one fixed by https://github.com/TREEcg/event-stream-client/commit/ca6d57b960454388414d03d689aad03f499b30d9

**Comment by pietercolpaert** [comment]
Regarding part 2 since part one is now fixed: just emit all metadata once the metadata extractor provided a response?

**Comment by brechtvdv** [comment]
Metadata is exposed so can be closed
