### ISSUE TITLE
Naming of the disablePolling argument

### ISSUE THREAD

**Issue by pietercolpaert** [TREEcg/event-stream-client#28]
I don’t think it’s disabling polling that is the intended feature. I think it’s the intended feature to `onlyReplicate` and to keep the replicated LDES in-sync

Can we rename this?

**Comment by brechtvdv** [comment]
Maybe call it: disableSynchronization ?

**Comment by pietercolpaert** [comment]
Agreed! However, make sure to keep the old property working for backwards compatibility reasons!

**Comment by brechtvdv** [comment]
Will be fixed here: https://github.com/TREEcg/event-stream-client/commit/31373ba83a586f3a9ec67192e86bac99804f39ec
