### ISSUE TITLE
Extending collections

### ISSUE THREAD

**Issue by Dexagod** [TREEcg/event-stream-client#3]
Say I want to have a collection of policies for the research group.
This collection of policies extends the policies of the faculty, which in turn extends the policies of the university.
Do we have / want a way to represent these kinds of collections in TREE?

**Comment by brechtvdv** [comment]
Better to move this to the TREE specification repo for further discussion.

IMO, specialized properties for extended collections should not be necessary. You can create 3 collections where the policies (tree:members) are shared among them
